services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  hub:
    container_name: hub
    build:
      context: ./hub
      dockerfile: Dockerfile
    ports:
      - "14223:14223"
    volumes:
      - hub_db:/hub/db
      - hub_images:/hub/images
      - ./config:/hub/config
      - ./chat/app/common:/hub/app/common
    restart: unless-stopped
    stdin_open: true
    tty: true
      
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "7346:7346"
    volumes:
      - node_images:/node/images
      - ./config:/node/config
      - /var/lib/Rueckgrat/models:/node/models
      - ./chat/app/common:/node/app/common
    stdin_open: true
    tty: true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"    

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../logs:/app
      - chat_cache:/chat/cache
      - /var/lib/Rueckgrat/models:/node/models
    stdin_open: true
    tty: true      
    restart: unless-stopped
    environment:
      - TITLE=Rueckgrat
      - PIXELFLUX_WAYLAND=true
      #- HARDEN_DESKTOP=true
      #- DISABLE_OPEN_TOOLS=true
      #- DISABLE_SUDO=true
      #- DISABLE_TERMINALS=true
      #- NO_DECOR=true
      #- RESTART_APP=true
    extra_hosts:
      - "${HUB_HOST}:${HUB_ADDR}"


  llama-server:
    container_name: llama-server
    image: ghcr.io/ggml-org/llama.cpp:server-${LLAMA_SERVER_SERVER}
    privileged: true
    volumes:
      - /var/lib/Rueckgrat/models:/models
    ports:
      - "${LLAMA_SERVER_PORT}:${LLAMA_SERVER_PORT}"
    restart: unless-stopped
    command: -m ${LLAMA_SERVER_MODEL} --host 0.0.0.0 --ctx-size ${LLAMA_SERVER_MAX_CONTEXT} --n-gpu-layers ${LLAMA_SERVER_GPU_LAYERS}

volumes:
  caddy_data:
  caddy_config:
  node_images:
  hub_db:
  hub_images:
  chat_cache: